name: terminalgpt
description: Access ChatGPT from your terminal.
version: 0.0.2
repository: https://github.com/rutvik110/tGPT

environment:
  sdk: ">=2.19.2 <3.0.0"
executables:
  tgpt: terminalgpt

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.0
  http: ^0.13.5
  mason_logger: ^0.2.5
  process_run: ^0.12.5+2
  path: ^1.8.0
